name: bill_splitter
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  avatar_stack: ^1.2.0
  badges: ^3.0.3
  calendar_date_picker2: ^0.4.6
  carousel_slider: ^4.2.1
  circular_profile_avatar: ^2.0.5
  crop_your_image: ^0.7.4
  dropdown_button2: ^2.0.0
  feature_discovery: ^0.14.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_tesseract_ocr: ^0.4.20
  fluttericon: ^2.0.0
  form_field_validator: ^1.1.0
  full_screen_image_null_safe: ^2.0.0
  get: 4.6.5
  get_storage: ^2.1.1
  http: ^0.13.5
  image: ^4.0.15
  image_picker: ^0.8.7
  intl: ^0.18.0
  list_tile_switch: ^1.0.0
  loader_overlay: ^2.2.0
  nb_utils: ^5.0.5
  onesignal_flutter: ^3.5.1
  path_provider: ^2.0.14
  stylish_bottom_bar: ^1.0.0
  supabase_flutter: ^1.5.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo/BS_icon.png"
  min_sdk_android: 25

flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
  assets:
    - .env
    - assets/images/undraw_Login.png
    - assets/images/undraw_signUp.png
    - assets/images/undraw_Forgot_password.png
    - assets/images/undraw_Mail_sent.png
    - assets/images/undraw_Mobile_payments.png
    - assets/images/undraw_Receipt.png
    - assets/images/undraw_Transfer_money.png
    - assets/images/undraw_My_password.png
    - assets/images/undraw_Empty.png
    - assets/images/undraw_Done.png
    - assets/logo/BS_icon.png
    - assets/tessdata/eng.traineddata
    - assets/tessdata/ind.traineddata
    - assets/tessdata_config.json
  uses-material-design: true
