name: bill_splitter
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  avatars: ^3.0.2
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  fluttericon: ^2.0.0
  get: 4.6.5
  nb_utils: ^5.0.5
  stylish_bottom_bar: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
  assets:
    - assets/images/undraw_Login.png
    - assets/images/undraw_signUp.png
    - assets/images/undraw_Forgot_password.png
    - assets/images/undraw_Mail_sent.png
    - assets/images/undraw_Mobile_payments.png
    - assets/images/undraw_Receipt.png
    - assets/images/undraw_Transfer_money.png
  uses-material-design: true
